crud/api/urls.py
from django.urls                    import path
from django.contrib.auth.decorators import login_required

from api import views

app_name = 'api'

urlpatterns = [
    path('tasks/', login_required(views.TasksView.as_view()), name='tasks'),
    path('tasks/<str:id>/', login_required(views.TaskView.as_view()), name='task'),
    path('tasks/<str:task_id>/chunks/', login_required(views.ChunksView.as_view()), name='chunks'),
    path('tasks/<str:task_id>/chunks/<str:id>/', login_required(views.ChunkView.as_view()), name='chunk'),
]

crud/chunks/urls.py
app_name = 'chunks'

urlpatterns = []

crud/crud/urls.py
from django.contrib import admin
from django.urls    import include, path, re_path
from crud           import views

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),

    re_path('', include('tasks.urls')),
    re_path(r'^chunks/', include('chunks.urls')),
    re_path(r'^api/', include('api.urls')),
]

crud/tasks/urls.py
from django.urls                    import path
from django.contrib.auth.decorators import login_required
from tasks                          import views

app_name = 'tasks'

urlpatterns = [
    path('', login_required(views.IndexView.as_view(), login_url='/login/'), name='index'),
    path('tasks/<int:pk>/', login_required(views.DetailView.as_view(), login_url='/login/'), name='detail'),
]

crud/chunks/models.py
import typing
import os

from datetime     import datetime, timedelta, timezone
from django.db    import models
from tasks.models import Task


# pylint: disable=no-member
class Chunk(models.Model):
	"""Chunk is a model for the chunks table."""
	title       = models.CharField(max_length=200)
	task        = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='chunks')
	finished_at = models.DateTimeField(blank=True, null=True)

	_WORK_START  = os.environ.get('WORK_START'  , '09:00')
	_WORK_END    = os.environ.get('WORK_END'    , '18:00')
	_BREAK_START = os.environ.get('BREAK_START' , '12:00')
	_BREAK_END   = os.environ.get('BREAK_END'   , '13:00')
	_WEEKENDS    = os.environ.get('WEEKENDS'    , '5,6')

	@property
	def duration(self: object) -> timedelta:
		"""duration is a property that returns the duration of the chunk."""
		if self.finished_at is None:
			return

		duration: timedelta = self.finished_at - self.started_at

		duration -= self.lunch_break

		duration -= self.out_of_work

		duration -= self.weekend

		return duration

	@property
	def started_at(self: object) -> datetime:
		"""started_at is a property that returns the started at of the chunk."""
		chunk_before: Chunk = self.task.chunks.filter(finished_at__lt=self.finished_at).order_by('-finished_at').first()
		return chunk_before.finished_at if chunk_before is not None else self.task.started_at

	def __str__(self) -> str:
		return str(self.title)

	def to_json(self) -> dict:
		"""to_json is a method that returns a json representation of the chunk."""
		return {
			'id'         : self.id,
			'title'      : self.title,
			'task'       : self.task.id,
			'finished_at': self.finished_at
		}

	def generate_time(self: object, time: str) -> datetime:
		"""generate_time is a method that returns a datetime object from a string."""
		return datetime.strptime(time, '%H:%M').replace(tzinfo=timezone.utc)

	@property
	def work_start(self: object) -> datetime:
		"""work_start is a property that returns the work start of the chunk."""
		return self.generate_time(self._WORK_START)

	@property
	def work_end(self: object) -> datetime:
		"""work_end is a property that returns the work end of the chunk."""
		return self.generate_time(self._WORK_END)

	@property
	def break_start(self: object) -> datetime:
		"""break_start is a property that returns the break start of the chunk."""
		return self.generate_time(self._BREAK_START)

	@property
	def break_end(self: object) -> datetime:
		"""break_end is a property that returns the break end of the chunk."""
		return self.generate_time(self._BREAK_END)

	@property
	def lunch_break(self: object) -> timedelta:
		"""lunch_break is a property that returns the lunch break of the chunk."""
		if self.finished_at is None:
			return timedelta()


		if self.started_at > self.break_end:
			return timedelta()

		if self.finished_at < self.break_start:
			return timedelta()

		if self.started_at < self.break_start:
			return self.break_start - self.started_at

		if self.finished_at > self.break_end:
			return self.finished_at - self.break_end

		return self.finished_at - self.started_at


	@property
	def out_of_work(self: object) -> timedelta:
		"""out_of_work is a property that returns the out of work of the chunk."""
		if self.finished_at is None:
			return timedelta()

		if self.started_at > self.work_end:
			return timedelta()

		if self.finished_at < self.work_start:
			return timedelta()

		if self.started_at < self.work_start:
			return self.work_start - self.started_at

		if self.finished_at > self.work_end:
			return self.finished_at - self.work_end

		return self.finished_at - self.started_at

	@property
	def weekend(self: object) -> timedelta:
		"""weekend is a property that returns the weekend of the chunk."""
		if self.finished_at is None:
			return timedelta()

		weekends: typing.List[int] = [int(weekend) for weekend in self._WEEKENDS.split(',')]

		if self.finished_at.weekday() in weekends:
			return timedelta()

		if self.started_at.weekday() in weekends:
			return timedelta()

		return timedelta()

		

crud/tasks/models.py
"""Task model"""

import typing

from datetime                   import datetime
from django.db                  import models
from django.contrib.auth.models import User

# pylint: disable=no-member
class Task(models.Model):
	"""Task is a model for the tasks table."""
	title       = models.CharField(max_length=200)
	description = models.TextField(blank=True, null=True)
	due_date    = models.DateTimeField()
	started_at  = models.DateTimeField(blank=True, null=True)
	user        = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')

	@property
	def progress(self: object) -> float:
		"""progress is a property that returns the progress of the task."""
		total_chunks = self.chunks.count()
		if total_chunks == 0:
			return 0

		finished_chunks = self.chunks.filter(finished_at__isnull=False).count()
		return finished_chunks / total_chunks * 100

	@property
	def estimated_seconds_left(self: object) -> int:
		"""estimated_seconds_left is a property that returns the estimated seconds left of the task."""
		if self.progress % 100 == 0:
			return 0

		estimated_time_left = (100 - self.progress) * (self.finished_at - self.started_at) / self.progress

		return int(estimated_time_left.total_seconds())

	@property
	def average_duration(self: object) -> int:
		"""average_duration is a property that returns the average duration of the task."""
		total_finished_chunks = self.chunks.filter(finished_at__isnull=False).count()
		if total_finished_chunks == 0:
			return 0

		total_duration = sum([
			chunk.duration.total_seconds() 
			for chunk in self.chunks.all()
			if chunk.duration is not None
		])

		return total_duration / total_finished_chunks / 3600 # in hours

	@property
	def finished_at(self: object) -> datetime:
		"""finished_at is a property that returns the finished at of the task."""
		return self.chunks.order_by('-finished_at').first().finished_at

	def __str__(self: object) -> str:
		return str(self.title)

	def to_json(self: object) -> dict:
		"""to_json is a method that returns a json representation of the task."""
		return {
			'id'         : self.id,
			'title'      : self.title,
			'description': self.description,
			'due_date'   : self.due_date,
			'started_at' : self.started_at,
			'user'       : self.user.id
		}

crud/chunks/views.py
from django.views     import generic

class ChunkView(generic.View):
	"""ChunkView is a generic class base view for the chunk endpoint."""
	pass

crud/tasks/views.py
import typing

from django.views                   import generic
from tasks.models                   import Task


# pylint: disable=no-member
class IndexView(generic.ListView):
	"""IndexView is a generic class base view for the index page."""
	template_name = 'tasks/index.html'
	context_object_name = 'tasks'

	def get_queryset(self) -> list[Task]:
		return Task.objects.filter(user=self.request.user)

class DetailView(generic.DetailView):
	"""DetailView is a generic class base view for the detail page."""
	model = Task
	template_name = 'tasks/detail.html'

crud/tasks/templates/components/lists/chunks.html
<form 
	x-data="{ 
		method     : 'POST', // POST | PUT | DELETE
		id         : null,
		title      : '',
		finishedAt : '',

		submit() {
			const url = this.id 
				? '{% url 'api:chunk' task_id=task.id id='__id__' %}'.replace('__id__', this.id)
				: '{% url 'api:chunks' task_id=task.id %}';

			const data = {
				title      : this.title.replace(/^・/gm, ''),
				finishedAt : this.finishedAt,
			};

			const options = {
				method: this.method,
				headers: {
					'Content-Type': 'application/json',
					'X-CSRFToken': '{{ csrf_token }}',
					'credentials': 'include'
				},
				body: JSON.stringify(data)
			};

			fetch(url, options)
				.then(() => window.location.reload())
				.catch(err => console.error(err));
		}
	}"
	@submit.prevent="submit()"
>
	<table class="w-full text-left rounded-lg overflow-hidden px-4 py-2 bg-white">
		<thead>
			<tr class="text-gray-800 border-b">
				<th class="px-4 py-2">No</th>
				<th class="px-4 py-2">Title</th>
				<th class="px-4 py-2">Finished at</th>
				<th class="px-4 py-2">Time spent</th>
				<th class="px-4 py-2">Actions</th>
			</tr>
		</thead>
		<tbody class="text-gray-700">
			{% for chunk in chunks %}
				{% include "components/list-items/chunk.html" %}
			{% endfor %}

			{% include "components/forms/add-chunk.html" %}
			</tbody>
		</table>
	</form>

crud/tasks/templates/components/lists/tasks.html
<form 
	x-data="{ 
		method     : 'POST', // POST | PUT | DELETE
		id         : null,
		title      : '',
		description: '',
		due_date   : '',

		submit() {
			const url = this.id 
				? '{% url 'api:task' id='__id__' %}'.replace('__id__', this.id)
				: '{% url 'api:tasks' %}';

			const data = {
				title: this.title,
				description: this.description,
				due_date: this.due_date
			};

			const options = {
				method: this.method,
				headers: {
					'Content-Type': 'application/json',
					'X-CSRFToken': '{{ csrf_token }}',
					'credentials': 'include'
				},
				body: JSON.stringify(data)
			};

			fetch(url, options)
				.then(() => window.location.reload())
				.catch(err => console.error(err));
		}
	}"
	@submit.prevent="submit()"
	>
	<table class="w-full text-left rounded-lg overflow-hidden px-4 py-2 bg-white">
		<thead>
			<tr class="text-gray-800 border-b">
				<th class="px-4 py-2">No</th>
				<th class="px-4 py-2">Title</th>
				<th class="px-4 py-2">Description</th>
				<th class="px-4 py-2">Due Date</th>
				<th class="px-4 py-2">Actions</th>
			</tr>
		</thead>
		<tbody class="text-gray-700">
			{% for task in tasks %}
				{% include "components/list-items/task.html" %}
			{% endfor %}

			<tr class="hover:bg-blue-50">
				{% include "components/forms/add-task.html" %}
			</tr>
		</tbody>
	</table>
</form>